package engine

// Register Providers

import (
	_ "github.com/djniche/test123/provider/10musume"
	_ "github.com/djniche/test123/provider/1pondo"
	_ "github.com/djniche/test123/provider/av-league"
	_ "github.com/djniche/test123/provider/avbase"
	_ "github.com/djniche/test123/provider/aventertainments"
	_ "github.com/djniche/test123/provider/c0930"
	_ "github.com/djniche/test123/provider/caribbeancom"
	_ "github.com/djniche/test123/provider/caribbeancompr"
	_ "github.com/djniche/test123/provider/dahlia"
	_ "github.com/djniche/test123/provider/duga"
	_ "github.com/djniche/test123/provider/faleno"
	_ "github.com/djniche/test123/provider/fanza"
	_ "github.com/djniche/test123/provider/fc2"
	_ "github.com/djniche/test123/provider/fc2hub"
	_ "github.com/djniche/test123/provider/gcolle"
	_ "github.com/djniche/test123/provider/getchu"
	_ "github.com/djniche/test123/provider/gfriends"
	_ "github.com/djniche/test123/provider/h0930"
	_ "github.com/djniche/test123/provider/h4610"
	_ "github.com/djniche/test123/provider/heydouga"
	_ "github.com/djniche/test123/provider/heyzo"
	_ "github.com/djniche/test123/provider/jav321"
	_ "github.com/djniche/test123/provider/javbus"
	_ "github.com/djniche/test123/provider/javfree"
	_ "github.com/djniche/test123/provider/kin8tengoku"
	_ "github.com/djniche/test123/provider/madouqu"
	_ "github.com/djniche/test123/provider/mgstage"
	_ "github.com/djniche/test123/provider/modelmediaasia"
	_ "github.com/djniche/test123/provider/muramura"
	_ "github.com/djniche/test123/provider/mywife"
	_ "github.com/djniche/test123/provider/pacopacomama"
	_ "github.com/djniche/test123/provider/pcolle"
	_ "github.com/djniche/test123/provider/sod"
	_ "github.com/djniche/test123/provider/theporndb"
	_ "github.com/djniche/test123/provider/tokyo-hot"
)
